const int STATE_DEFAULT = 0;

const int STATE_LAYOUT_GRID = 101;
const int STATE_LAYOUT_FULL_STRETCHED = 102;
const int STATE_LAYOUT_SCROLLABLE_FORM = 103;
const int STATE_LAYOUT_SILVERS = 104;
const int STATE_LAYOUT_SILVERS_PAGES = 105;

const int STATE_MESSAGE = 210;

const int STATE_MODULE_PERSON = 200;
const int STATE_MODULE_ALBUM = 300;
const int STATE_MODULE_CONFIGURATION = 800;
const int STATE_MODULE_CONTACT = 600;
const int STATE_MODULE_CONTACT_ONE = 601;
const int STATE_MODULE_CONTACT_NUMBER = 602;
const int STATE_MODULE_CONTACT_SPINNER = 690;
const String MODULE_CONTACT_CACHE = '<MODULE_CONTACT_CACHE>';

const int STATE_SHARE_CONTENT = 700;
const int STATE_SHARE_CONTENT_CAMERA = 701;

const int STATE_ERROR_UNEXPECTED = 991;
