const int STATE_DEFAULT = 0;

const int STATE_LAYOUT_GRID = 101;
const int STATE_LAYOUT_FULL_STRETCHED = 102;
const int STATE_LAYOUT_SCROLLABLE_FORM = 103;
const int STATE_LAYOUT_SILVERS = 104;
const int STATE_LAYOUT_SILVERS_PAGES = 105;

const int STATE_APP_PERSON = 2;
const int STATE_APP_ALBUM = 3;
const int STATE_APP_CONTACT = 6;
const int STATE_APP_CONTACT_CONFIGURATION = 600;
const int STATE_APP_CONTACT_ONE = 601;
const int STATE_APP_CONTACT_NUMBER = 602;
const int STATE_APP_CONTACT_SPINNER = 690;

const int STATE_SHARE_CONTENT = 7;
const int STATE_SHARE_CONTENT_CAMERA = 701;

const int STATE_ERROR_UNEXPECTED = 991;
